# Site settings
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Team ZEUS"
theme = "agency"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Your description"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "your@email.com"


	# Navigation
	[params.navigation]
		brand = "Home"
		services = "About"
		portfolio = "Projects"
		about = "Media"
		team = "Team"
		contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "High Performance Electric Motorcycle Racing"
		subtitle = "Welcome to Team ZEUS!"
		buttonText = "Tell me more"


	# Services section
	[params.services]
		title = "about"
		subtitle = "Here at Team ZEUS, what do we even do? Click an icon to visit the team's website! TODO - revise"

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-desktop"
                title = "Software Team"
                description = "Freakin Ossum (That's us!)"
				link = "https://www.google.ca/"

            [[params.services.row.list]]
                icon = "fa-bolt"
                title = "Electrical Team"
                description = "Description of the electrical team?"
				link = "https://www.google.ca/"

            [[params.services.row.list]]
                icon = "fa-cogs"
                title = "Mechanical Team"
                description = "We can make as many elements as we want, and pick from 100's of icons; just modify config.toml - TODO revise"
				link = "https://www.google.ca/"

	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Projects"
		subtitle = "An overview of some of our current and past projects (add or remove as many as we want! just make a yaml file in data/projects folder - TODO revise"

		[params.portfolio.modal]
            buttonText = "Close project"


    # About section
	[params.about]
		title = "Media"
		subtitle = "See Team ZEUS in the media and giving back to the community through education!"
		displaycount = "9"
		
		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "March 20, 2014"
			title = "The Gauntlet"
			description = "Engineers build a racing motorcycle"
			link = "http://www.archive.thegauntlet.ca/story/engineers-build-racing-motorcycle"

		[[params.about.events]]
			img = "2.jpg"
			date = "March 20, 2014"
			title = "Metro Calgary"
			description = "‘Team Zeus’ building electric superbike at the University of Calgary"
			link = "http://Metro Calgarynews.ca/news/calgary/979037/team-zeus-building-electric-superbike-at-the-university-of-calgary/"

		[[params.about.events]]
			img = "3.jpg"
			date = "Episode 74"
			title = "Green Energy Futures"
			description = "Meet Team Zeus - An electric motorbike racing team from the University of Calgary"
			link = "http://www.greenenergyfutures.ca/episode/74-meet-team-zeus-electric-motorbike-racing-team-university-calgary"

		[[params.about.events]]
			img = "4.jpg"
			date = "May 5, 2014"
			title = "Huffington Post"
			description = "The University of Calgary Club That Built an Electric Motorcycle"
			link = "http://www.huffingtonpost.ca/david-dodge/electric-motorcycles_b_5268926.html"
			
		[[params.about.events]]
			img = "5.jpg"
			date = "May 8, 2014"
			title = "Telus Spark"
			description = "'Your Inner Engineer' Night"
			link = ""
			
		[[params.about.events]]
			img = "7.jpg"
			date = "September 11, 2014"
			title = "Beakerhead"
			description = ""
			link = ""
			
		[[params.about.events]]
			img = "8.jpg"
			date = "September 16, 2014"
			title = "UToday"
			description = "Team ZEUS unveils Zephyr superbike at national race in Utah"
			link = "http://www.ucalgary.ca/utoday/issue/2014-09-16/team-zeus-unveils-zephyr-superbike-national-race-utah"
			
		[[params.about.events]]
			img = "9.jpg"
			date = "September 21, 2014"
			title = "Metro Calgary"
			description = "University of Calgary’s electric superbike turns heads at eMotoRacing event in Utah"
			link = "http://Metro Calgarynews.ca/news/calgary/1161897/university-of-calgarys-electric-superbike-turns-heads-at-emotoracing-event-in-utah/"
			
		[[params.about.events]]
			img = "10.jpg"
			date = "November 14, 2014"
			title = "Third Academy"
			description = "School visit to the Third Academy"
			link = ""
			
		[[params.about.events]]
			img = "11.jpg"
			date = "December 2, 2014"
			title = "Inside Motorcycles"
			description = "It's impossible not to be inspired by Team Zeus and its University of Calgary-based electric racer project"
			link = "http://suclubs.orgsync.com/org/teamzeus/article"


	# Team section
	[params.team]
		title = "Our amazing team"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "1.jpg"
			name = "Kay Garland"
			position = "Lead Designer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "2.jpg"
			name = "Larry Parker"
			position = "Lead Marketer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "3.jpg"
			name = "Diana Pertersen"
			position = "Lead Developer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

	# Client section
	# All the clients' logos are stored under 'static/img/logos'.
	# Replace them with your clients's logos.
	[[params.clients]]
		logo = "envato.jpg"
		link = "#"

	[[params.clients]]
		logo = "designmodo.jpg"
		link = "#"

	[[params.clients]]
		logo = "themeforest.jpg"
		link = "#"

	[[params.clients]]
		logo = "creative-market.jpg"
		link = "#"


	# Contact section
	[params.contact]
		title = "Contact us"
		subtitle  = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "#"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
